### ISSUE TITLE
Bug with mvn (build keeps failing)

### ISSUE THREAD

**Issue by annemariecabs** [googleinterns/step174-2020#11]
When I run ``mvn package appengine:run`` in my portfolio folder, the build fails, and gives me this error: 
``[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.2.0:run (default-cli) on project portfolio: Failed to run devappserver: com.google.cloud.tools.appengine.operations.cloudsdk.process.ProcessHandlerException: com.google.cloud.tools.appengine.AppEngineException: Non zero exit: 1 -> [Help 1]``

Notably, this does not seem to be a result of my code, as I ran it on the original STEP repository project "stanley" in week 2 examples, and it runs into the same error (even though this has previously worked). I have tried to fix this by disconnecting and reconnecting to the Cloud Shell, running ``mvn clean``, and looking at the article the error directed me to (https://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException).

**Comment by ykjchen** [comment]
Hey @annemariecabs could you point me to the branch/commit that you're failing on? I can see if the failure reproduces for me.

**Comment by annemariecabs** [comment]
Sure. I haven't actually committed the changes for today up to my fork. However, I will push them up right now. It fails on the current version of the project I'm working on (as it's called within the portfolio folder.

**Comment by ykjchen** [comment]
Does it also fail if you try to build from master?

**Comment by ykjchen** [comment]
This was resolved by rebooting the cloud client.
