### ISSUE TITLE
Add Perspective Demo

### ISSUE THREAD

**Issue by jelares** [googleinterns/step174-2020#91]

**Comment by annemariecabs** [comment]
- [ ]  Build out HTML user interface with a text prompt and display (& add CSS styling) 
- [ ] Add back end servlet and PerspectiveAnalysis class which use Perspective API to get scores for text entered
- [ ] Get results from servlet using JS and then display them on the Perspective Demo page
- [ ] Present this to rest of group

**Comment by annemariecabs** [comment]
- [ ]  Review PR (#86) for Pesrpective Demo (@jelares & @UdayKalra)
